name: Create envfile

on: [ push ]

jobs:    
     create-envfile:
           runs-on: ubuntu-latest
           steps:
              - name: Env create
                run: |
                   touch .env
                   echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
                   echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
                   echo REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} >> .env
                   echo REDIRECT_URI=${{ secrets.REDIRECT_URI }} >> .env
                   cat .env
